name: mlhub_flutter
description: "A Flutter app for MLHub."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # To make InheritedWidget easier to use and more reusable.
  provider: ^6.1.2

  # For fixing the size of the desktop app window.
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main
  
  # For choosing the input audio language option.
  dropdown_search: ^5.0.6

  # For drag and drop file functionality.
  desktop_drop: ^0.4.4

  # For choosing the file from local.
  file_picker: ^8.0.0+1

  # For detecting the input file type.
  mime: ^1.0.5

  # For querying the version number of the app.
  package_info_plus: ^5.0.1

  # For keeping track of the commands to write on the log page.
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
