name: mlhub_flutter
description: "A Flutter app for MLHub."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # To make InheritedWidget easier to use and more reusable.
  provider: ^6.1.2

  # For fixing the size of the desktop app window.
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main
  
  # For drag and drop file functionality.
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
